services:
  leaderboard:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      PORT: 3000
      MONGO_URL: mongodb://mongo:27017/broomstick-joyride
      ALLOWED_ORIGINS: http://localhost:8000
      NODE_ENV: prod

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
