services:
  leaderboard:
    build: ./leaderboard
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./leaderboard:/app
    environment:
      BACKEND_PORT: 3000
      NODE_ENV: prod
